### ISSUE TITLE
Interpretation issue: Negative value without explicitly specifying -x & -y flag

### ISSUE THREAD

**Issue by RatedR9** [udevsharold/locsim#4]
if lat and long are negative number locsim says invalid option I use \ it still get error rootful also has this problem, and when open Apple map/Google map to share with Locsim shortcuts it says mkerrordomain error 1,but iOS 14 works

**Comment by udevsharold** [comment]
You need to quote them:
`locsim start "-1.4873828" "0.3827432"`

As for the error, that looks like Shortcuts issue, probably the API changed on iOS 15, not an issue of locsim.

**Comment by RatedR9** [comment]
I forget to say I use quote but get invalid option 
![98ECF1C1-2A54-4B2D-8B2B-ECD84F61157E](https://github.com/udevsharold/locsim/assets/62322670/0f0dd76d-d6f8-4085-ac15-f52df90ab1d6)

**Comment by udevsharold** [comment]
Hmm that seems like interpretation issue since no flag specified. I'll have a look when I got the time. In the mean time you could just explicitly specify the flag:
`locsim start -x "-1.4873828" -y "0.3827432"`

**Comment by RatedR9** [comment]
it worked,thank you

**Comment by udevsharold** [comment]
> shortcuts it says mkerrordomain error 1

I figured that in >= iOS 15, you have to convert the map link into "Location" first before getting their lat/lon. I've updated the shortcut in README to fix this.

**Comment by RatedR9** [comment]
> > shortcuts it says mkerrordomain error 1
> 
> I figured that in >= iOS 15, you have to convert the map link into "Location" first before getting their lat/lon. I've updated the shortcut in README to fix this.
can you share the shortcut with icloud link?I don’t know how to direct install
