### ISSUE TITLE
Tested and working on iOS 15.8

### ISSUE THREAD

**Issue by BreakfastSerial** [udevsharold/locsim#5]
I've just tested locsim on iOS 15.8 and can confirm it's working as expected. Thank you for your hard work!

 * iPhone SE Gen. 1
 * iOS 15.8
 * Jailbreak, rootless, palera1n
 * Sileo App Store, Procursus Repo
 * locsim verion 1.1.8-1

**Comment by cymouseX** [comment]
i compile but not work on rootless, can ou send me .deb file? pls
